[package]
name = "srane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# image = "0.24"
# rand = "0.8.5"
eframe = "0.22.0"
egui = "0.22.0"
