[package]
name = "srane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
eframe = "0.28"
egui = "0.28"
tracing = "0.1"
tracing-subscriber = "0.3"
ocl = "0.19"
